# Generated by Django 2.0.4 on 2018-04-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0002_auto_20170827_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Standup',
        ),
        migrations.AlterModelOptions(
            name='standup',
            options={'ordering': ('week_start',)},
        ),
        migrations.RenameField(
            model_name='standup',
            old_name='standup_week_start',
            new_name='week_start',
        ),
    ]
